.TH "Xennet::Info" 3 "19 Sep 2008" "Version 0.1.0" "Xennet C++ Network Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Xennet::Info \- The \fBInfo\fP class provides library information.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <xenInfo.hpp>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInfo\fP ()"
.br
.ti -1c
.RI "virtual \fB~Info\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBgetVersion\fP ()"
.br
.RI "\fIGet \fBXennet\fP library version. \fP"
.ti -1c
.RI "static std::string \fBgetDescription\fP ()"
.br
.RI "\fIGet library description. \fP"
.ti -1c
.RI "static std::string \fBgetCopyright\fP ()"
.br
.RI "\fIGet the copyright/license for the \fBXennet\fP library. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBInfo\fP class provides library information. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Xennet::Info::Info ()"
.PP
Default constructor 
.SS "Xennet::Info::~Info ()\fC [virtual]\fP"
.PP
Default destructor 
.SH "Member Function Documentation"
.PP 
.SS "std::string Xennet::Info::getVersion ()\fC [static]\fP"
.PP
Get \fBXennet\fP library version. 
.PP
.SS "std::string Xennet::Info::getDescription ()\fC [static]\fP"
.PP
Get library description. 
.PP
.SS "std::string Xennet::Info::getCopyright ()\fC [static]\fP"
.PP
Get the copyright/license for the \fBXennet\fP library. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Xennet C++ Network Library from the source code.
