.TH "libXennet/src/xenMain.hpp" 3 "20 Sep 2008" "Version 0.1.0" "Xennet C++ Network Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libXennet/src/xenMain.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <string>\fP
.br
\fC#include <list>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBXENNET_LIB_VERSION\fP   '0.0.1'"
.br
.RI "\fIDefine XENNET_LIB_VERSION. \fP"
.ti -1c
.RI "#define \fBDEFAULT_MAX_DATA_SIZE\fP   1000"
.br
.RI "\fIDefine DEFAULT_MAX_DATA_SIZE. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define DEFAULT_MAX_DATA_SIZE   1000"
.PP
Define DEFAULT_MAX_DATA_SIZE. 
.PP
.SS "#define XENNET_LIB_VERSION   '0.0.1'"
.PP
Define XENNET_LIB_VERSION. 
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Xennet C++ Network Library from the source code.
