.TH "Xennet" 3 "19 Sep 2008" "Version 0.1.0" "Xennet C++ Network Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Xennet \- The \fBXennet\fP namespace.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSocketAddress\fP"
.br
.ti -1c
.RI "class \fBInfo\fP"
.br
.RI "\fIThe \fBInfo\fP class provides library information. \fP"
.ti -1c
.RI "class \fBPacketBase\fP"
.br
.ti -1c
.RI "class \fBServerSocketBase\fP"
.br
.ti -1c
.RI "class \fBSocketAddressBase\fP"
.br
.RI "\fI\fBSocketAddressBase\fP is inherited by the OS-specific \fBSocketAddress\fP class. \fP"
.ti -1c
.RI "class \fBSocketBase\fP"
.br
.RI "\fI\fBSocketBase\fP is inherited by the OS-specific Socket class . \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBXennet\fP namespace. 

The \fBXennet\fP namespace contains all of the classes and functions in the library. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Xennet C++ Network Library from the source code.
