.TH "Xennet::ServerSocketBase" 3 "19 Sep 2008" "Version 0.1.0" "Xennet C++ Network Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Xennet::ServerSocketBase \- 
.SH SYNOPSIS
.br
.PP
\fC#include <xenServerSocketBase.hpp>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServerSocketBase\fP ()"
.br
.ti -1c
.RI "virtual \fB~ServerSocketBase\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetMaxDataSize\fP (int maxSize)"
.br
.ti -1c
.RI "virtual int \fBgetMaxDataSize\fP (void)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBmaxDataSize\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Xennet::ServerSocketBase::ServerSocketBase ()"
.PP
Default constructor 
.SS "Xennet::ServerSocketBase::~ServerSocketBase ()\fC [virtual]\fP"
.PP
Default destructor 
.SH "Member Function Documentation"
.PP 
.SS "void Xennet::ServerSocketBase::setMaxDataSize (int maxSize)\fC [virtual]\fP"
.PP
.SS "int Xennet::ServerSocketBase::getMaxDataSize (void)\fC [virtual]\fP"
.PP
.SH "Member Data Documentation"
.PP 
.SS "int \fBXennet::ServerSocketBase::maxDataSize\fP\fC [protected]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Xennet C++ Network Library from the source code.
