.TH "libXennet/src/xenSocketAddressBase.hpp" 3 "20 Sep 2008" "Version 0.1.0" "Xennet C++ Network Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libXennet/src/xenSocketAddressBase.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'xenMain.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBXennet\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXennet::SocketAddressBase\fP"
.br
.RI "\fI\fBSocketAddressBase\fP is inherited by the OS-specific \fBSocketAddress\fP class. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Xennet C++ Network Library from the source code.
